### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by jason274373** [alibaba-edu/High-Precision-Congestion-Control#4]
When compiling this project, some problems occurs. (ubuntu+python 3.7.3) 

The erro information is as follows:
Waf: The wscript in '/home/hpcc' is unreadable
Traceback (most recent call last):
  File "/home/hpcc/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Scripting.py", line 87, in waf_entry_point
    set_main_module(Context.run_dir+os.sep+Context.WSCRIPT_FILE)
  File "/home/hpcc/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Scripting.py", line 112, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/home/hpcc/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Context.py", line 281, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/hpcc/wscript", line 105
    print name.ljust(25),
             ^
SyntaxError: invalid syntax

Does this have anything to do with the python version?

**Comment by liyuliang001** [comment]
Did you try using python 2.x?

**Comment by Wsky51** [comment]
Hi，I have the same problem, change to python 2.x is not a good idea. I found when I build the project with the command 
`sudo CC='gcc-5' CXX='g++-5' ./waf configure` it works well . Remember the "sudo" in the first place.  so have a try !

**Comment by Jiawei1996** [comment]
python3 does not support the syntax like `print "hello"`, one should use python2 instead.
